# 듣기 3번 대화 50개 — (벌, 물음, 여(A) 한 줄, 남(B) 한 줄, 여 뜻, 남 뜻). 물음·보기는 그대로 두고 소리만 대화로.
D = {
1: [
 ("Ở Nhật anh Hiroki làm nghề gì?", "Ở Nhật anh làm kỹ sư phải không, anh Hiroki?", "Không, ở Nhật tôi làm kế toán ở ngân hàng.", "히로키 씨, 일본에서 엔지니어로 일하셨죠?", "아니요, 일본에서 저는 은행에서 회계사로 일했어요."),
 ("Ngân hàng của anh ấy có bao nhiêu nhân viên?", "Ngân hàng của anh có khoảng 50 nhân viên à?", "Không, ngân hàng của tôi có hơn 100 nhân viên.", "당신 은행은 직원이 50명쯤이에요?", "아니요, 우리 은행은 직원이 100명이 넘어요."),
 ("Brian dạy tiếng Anh ở quận nào?", "Anh Brian dạy tiếng Anh ở Quận 1 hả?", "Không, tôi dạy ở trường ILA, Quận 2.", "브라이언 씨는 1군에서 영어를 가르치죠?", "아니요, 저는 2군 ILA 학교에서 가르쳐요."),
 ("Anh ấy dạy mấy ngày một tuần?", "Anh dạy mấy ngày một tuần?", "Tôi dạy năm ngày một tuần, từ 9 giờ sáng đến 11 giờ rưỡi.", "일주일에 며칠 가르쳐요?", "일주일에 5일, 아침 9시부터 11시 반까지 가르쳐요."),
 ("Buổi chiều Hiroki làm việc từ mấy giờ đến mấy giờ?", "Buổi chiều anh làm việc từ mấy giờ đến mấy giờ?", "Buổi chiều tôi làm việc từ 2 giờ đến 7 giờ tối.", "오후에는 몇 시부터 몇 시까지 일해요?", "오후에는 2시부터 저녁 7시까지 일해요."),
 ("Hôm qua anh ấy vào phòng số mấy?", "Hôm qua anh vào phòng số 301 à?", "Không, hôm qua tôi vào nhầm phòng số 308.", "어제 301호에 들어갔어요?", "아니요, 어제 저는 308호에 잘못 들어갔어요."),
 ("Chị Loan làm việc ở đâu?", "Chị Loan làm việc ở ngân hàng phải không?", "Không, chị ấy làm kỹ sư ở công ty máy tính.", "로안 씨는 은행에서 일하죠?", "아니요, 그녀는 컴퓨터 회사에서 엔지니어로 일해요."),
 ("Dạo này chị ấy thế nào?", "Dạo này tôi rất bận vì buổi sáng tôi đi học, buổi chiều tôi đi làm.", "Chị cố gắng nhé!", "요즘 저는 오전엔 학교에 가고 오후엔 일하러 가서 아주 바빠요.", "힘내세요!"),
 ("Cô ấy sắp đi đâu?", "Anh ơi, tôi sắp đi ăn trưa với anh Brian.", "Ừ, chị đi nhé.", "저기요, 저 곧 브라이언 씨와 점심 먹으러 가요.", "네, 다녀오세요."),
 ("Siêu thị có bao nhiêu nhân viên?", "Siêu thị này có khoảng 100 nhân viên phải không?", "Không, siêu thị này nhỏ, chỉ có khoảng 20 nhân viên.", "이 마트는 직원이 100명쯤 되죠?", "아니요, 이 마트는 작아서 직원이 20명쯤뿐이에요."),
],
2: [
 ("Chị ấy làm việc ở đâu?", "Tôi làm thư ký ở một công ty máy tính, còn anh?", "Tôi làm việc ở ngân hàng.", "저는 컴퓨터 회사에서 비서로 일해요, 당신은요?", "저는 은행에서 일해요."),
 ("Anh ấy thường làm gì vào cuối tuần?", "Cuối tuần anh thường học tiếng Việt à?", "Không, cuối tuần tôi thường đi chơi với bạn bè.", "주말에 보통 베트남어를 공부해요?", "아니요, 주말에 저는 보통 친구들과 놀러 가요."),
 ("Hôm nay chị ấy ăn sáng lúc mấy giờ?", "Hôm nay tôi ăn sáng trễ, lúc 9 giờ.", "Còn tôi ăn sáng lúc 7 giờ.", "오늘 저는 아침을 늦게, 9시에 먹었어요.", "저는 7시에 아침을 먹었어요."),
 ("Anh ấy đi làm bằng gì?", "Anh đi làm bằng tắc xi hả?", "Không, tôi thường đi làm bằng xe buýt.", "택시로 출근해요?", "아니요, 저는 보통 버스로 출근해요."),
 ("Chị ấy đến công ty lúc mấy giờ?", "Nhà tôi hơi xa nên tôi thường đến công ty lúc 7 giờ 40.", "Còn tôi thường đến lúc 8 giờ.", "우리 집이 조금 멀어서 저는 보통 7시 40분에 회사에 도착해요.", "저는 보통 8시에 도착해요."),
 ("Cô ấy dạy ở đâu?", "Tôi đang dạy tiếng Anh ở Trường ILA, Quận 2.", "Công ty tôi ở Quận 1.", "저는 2군 ILA 학교에서 영어를 가르치고 있어요.", "우리 회사는 1군에 있어요."),
 ("Tối nay họ sẽ làm gì?", "Tối nay chúng ta đi ăn tối ở quán ăn gần công ty nhé?", "Ừ, quán đó ngon lắm.", "오늘 저녁 회사 근처 식당에 저녁 먹으러 갈까요?", "응, 그 식당 아주 맛있어요."),
 ("Nhà hàng ở đâu?", "Anh có biết nhà hàng nào ngon không?", "Tôi biết một nhà hàng ở Quận 1, món ăn ngon lắm.", "맛있는 식당 아는 데 있어요?", "1군에 있는 식당을 하나 알아요, 음식이 아주 맛있어요."),
 ("Chị ấy thế nào?", "Hôm nay tôi hơi mệt nên không đi chơi.", "Vậy chị nghỉ nhé.", "오늘 저는 조금 피곤해서 놀러 안 가요.", "그럼 쉬세요."),
 ("Anh ấy làm việc từ mấy giờ đến mấy giờ?", "Anh làm việc cả ngày à?", "Không, tôi làm việc từ 2 giờ đến 7 giờ, buổi sáng tôi đi học.", "하루 종일 일해요?", "아니요, 저는 2시부터 7시까지 일하고, 오전엔 학교에 가요."),
],
3: [
 ("Bây giờ họ đi đâu?", "Bây giờ chúng ta đi bưu điện hả anh?", "Không, chúng ta đi mua sách ở nhà sách FAHASA.", "지금 우리 우체국에 가는 거죠?", "아니요, 우리는 파하사 서점에 책 사러 가요."),
 ("Nhà sách FAHASA số mấy?", "Nhà sách FAHASA ở số 14 phải không?", "Không, ở số 40 đường Nguyễn Huệ.", "파하사 서점은 14번지에 있죠?", "아니요, 응우옌후에 거리 40번지에 있어요."),
 ("Hôm nay nhà sách giảm giá bao nhiêu?", "Hôm nay nhà sách giảm giá 13% à?", "Không, hôm nay nhà sách giảm giá 30%.", "오늘 서점이 13% 할인해요?", "아니요, 오늘 서점은 30% 할인해요."),
 ("Sao David biết nhà sách giảm giá?", "Sao anh biết nhà sách giảm giá?", "Vì anh Brian nói với tôi.", "서점이 할인하는 걸 어떻게 알아요?", "브라이언 씨가 말해 줬거든요."),
 ("Dorothy đi đâu?", "Anh cho tôi đến trường Nhân văn, số 10, Quận 1.", "Vâng, được ạ.", "1군 10번지 인문대로 가 주세요.", "네, 알겠습니다."),
 ("Nhà hàng đó ở đâu?", "Nhà hàng đó ở Quận 7 à?", "Không, ở Quận 1, bia tươi ở đó rất ngon.", "그 식당은 7군에 있어요?", "아니요, 1군에 있어요, 거기 생맥주가 아주 맛있어요."),
 ("Tối nay Lee mời ai đi uống bia?", "Tối nay anh mời ai đi uống bia?", "Tôi mời anh Min và anh Hiroki.", "오늘 저녁 누구를 맥주 마시러 초대해요?", "민 씨와 히로키 씨를 초대해요."),
 ("Hiroki đã đi tham quan ở đâu?", "Anh Hiroki đã đi tham quan ở đâu?", "Tôi đã đi tham quan Nhà thờ Đức Bà và Bảo tàng Lịch sử.", "히로키 씨는 어디를 구경했어요?", "저는 노트르담 성당과 역사박물관을 구경했어요."),
 ("Ngày mai Vân rảnh từ mấy giờ?", "Ngày mai tôi bận buổi sáng, nhưng tôi rảnh từ 2 giờ chiều.", "Vậy 3 giờ chúng ta gặp nhau nhé.", "내일 저는 오전엔 바쁘지만 오후 2시부터 한가해요.", "그럼 3시에 만나요."),
 ("Từ đây đến sân bay mất bao lâu?", "Từ đây đến sân bay mất bao lâu, anh?", "Đi tắc xi mất khoảng 30 phút.", "여기서 공항까지 얼마나 걸려요?", "택시로 30분쯤 걸려요."),
],
4: [
 ("Nhà sách ở đâu?", "Nhà sách FAHASA ở Quận 7 phải không anh?", "Không, ở đường Nguyễn Huệ, Quận 1.", "파하사 서점은 7군에 있죠?", "아니요, 1군 응우옌후에 거리에 있어요."),
 ("Từ nhà Lan đến công ty mất bao lâu?", "Từ nhà tôi đến công ty mất khoảng 30 phút.", "Nhà tôi gần, chỉ mất 10 phút.", "우리 집에서 회사까지 30분쯤 걸려요.", "우리 집은 가까워서 10분밖에 안 걸려요."),
 ("Họ sẽ gặp nhau lúc mấy giờ?", "Chúng ta gặp nhau lúc 7 giờ tối ở quán cà phê nhé?", "Được, 7 giờ tối nhé.", "우리 저녁 7시에 카페에서 만날까요?", "좋아요, 저녁 7시에요."),
 ("Anh ấy đi Đà Nẵng bằng gì?", "Tuần sau anh đi Đà Nẵng bằng xe buýt à?", "Không, tôi đi bằng máy bay.", "다음 주에 버스로 다낭에 가요?", "아니요, 비행기로 가요."),
 ("Siêu thị mở cửa lúc mấy giờ?", "Siêu thị mở cửa lúc mấy giờ, anh?", "Siêu thị mở cửa từ 8 giờ sáng đến 10 giờ tối.", "마트는 몇 시에 문을 열어요?", "마트는 아침 8시부터 밤 10시까지 열어요."),
 ("Cô ấy đang ở đâu?", "Bây giờ tôi đang ở bưu điện, tôi gửi thư cho bố mẹ.", "Vậy tôi chờ chị ở nhà sách nhé.", "지금 저는 우체국에서 부모님께 편지를 부치고 있어요.", "그럼 서점에서 기다릴게요."),
 ("Nhà của Nam gần hay xa công ty?", "Nhà anh có xa công ty không, anh Nam?", "Không, nhà tôi gần lắm, tôi đi bộ đi làm.", "남 씨, 집이 회사에서 멀어요?", "아니요, 우리 집은 아주 가까워서 걸어서 출근해요."),
 ("Hôm nay nhà sách giảm giá bao nhiêu?", "Hôm nay nhà sách giảm giá 10% phải không?", "Không, hôm nay giảm giá 20%.", "오늘 서점이 10% 할인하죠?", "아니요, 오늘은 20% 할인해요."),
 ("Chị ấy đi làm lúc mấy giờ?", "Tôi đi làm lúc 7 giờ rưỡi sáng, còn anh?", "Tôi đi làm lúc 8 giờ rưỡi.", "저는 아침 7시 반에 출근해요, 당신은요?", "저는 8시 반에 출근해요."),
 ("Cuối tuần họ đi đâu?", "Cuối tuần chúng ta đi phố đi bộ nhé?", "Ừ, ở đó rất đông và vui.", "주말에 우리 보행자 거리에 갈까요?", "응, 거기는 사람이 많고 즐거워요."),
],
5: [
 ("Anh ấy thường làm gì sau khi ăn tối?", "Sau khi ăn tối anh thường học tiếng Việt à?", "Không, tôi thường xem tivi với gia đình.", "저녁 먹은 뒤에 보통 베트남어를 공부해요?", "아니요, 저는 보통 가족과 TV를 봐요."),
 ("Chị ấy thích làm gì?", "Tôi rất thích nghe nhạc và đọc sách.", "Còn tôi thích xem phim.", "저는 음악 듣기와 책 읽기를 아주 좋아해요.", "저는 영화 보는 걸 좋아해요."),
 ("Hôm qua em ấy đi ngủ lúc mấy giờ?", "Hôm qua em đi ngủ lúc mấy giờ?", "Em thức khuya học bài nên đi ngủ lúc 1 giờ.", "어제 몇 시에 잤어?", "늦게까지 공부해서 1시에 잤어요."),
 ("Cuối tuần Nam thường làm gì?", "Anh Nam, cuối tuần anh thường làm gì?", "Tôi thường đi chơi với bạn bè hay xem phim ở nhà.", "남 씨, 주말에 보통 뭐 해요?", "보통 친구들과 놀러 가거나 집에서 영화를 봐요."),
 ("Ai nấu ăn trong gia đình?", "Ai nấu ăn trong gia đình anh?", "Mẹ tôi thường nấu ăn, thỉnh thoảng bố tôi cũng nấu ăn.", "가족 중 누가 요리해요?", "보통 어머니가 요리하고, 가끔 아버지도 해요."),
 ("Buổi sáng anh ấy làm gì?", "Buổi sáng anh thường làm gì?", "Tôi thức dậy lúc 6 giờ, tập thể dục rồi ăn sáng.", "아침에 보통 뭐 해요?", "6시에 일어나서 운동하고 아침을 먹어요."),
 ("Tối nay họ sẽ làm gì?", "Tối nay chúng ta đi xem phim nhé, phim mới hay lắm.", "Được, mấy giờ?", "오늘 저녁 영화 보러 가요, 새 영화가 아주 재미있어요.", "좋아요, 몇 시에요?"),
 ("Chị ấy có thường ăn sáng không?", "Tôi thường không ăn sáng vì tôi đi làm sớm.", "Vậy chị uống cà phê nhé.", "저는 일찍 출근해서 보통 아침을 안 먹어요.", "그럼 커피라도 드세요."),
 ("Em ấy học tiếng Việt lúc nào?", "Em học tiếng Việt lúc nào?", "Buổi tối em thường học khoảng một tiếng.", "베트남어는 언제 공부해?", "저녁에 보통 한 시간쯤 공부해요."),
 ("Sao hôm nay anh ấy mệt?", "Sao hôm nay anh mệt vậy?", "Vì tối qua tôi thức khuya xem phim.", "오늘 왜 그렇게 피곤해요?", "어젯밤 늦게까지 영화를 봤거든요."),
],
}
