JOBS = {
"ngày xưa": "An old-fashioned Vietnamese village scene from long ago, sepia tones, a farmer with buffalo and thatched houses",
"năm mới": "Vietnamese Lunar New Year celebration with pink peach blossoms, red envelopes and fireworks",
"về sớm": "A happy office worker leaving the office early in the afternoon with a bag, clock on the wall showing 4 o'clock",
"giờ phút": "A large hourglass with sand falling, warm light",
"tôi đi nhé": "A person waving goodbye at a doorway, holding a bag, smiling",
"chào các bạn": "A friendly teacher waving hello to a group of smiling students",
"đồ uống": "Three different drinks: a glass of iced coffee, a glass of orange juice and a bottle of water",
"cà phê sữa": "A tall glass of Vietnamese iced coffee with condensed milk layered at the bottom",
"nước dừa": "A fresh green coconut with a straw",
"nước chanh": "A glass of lemonade with ice and lime slices",
"rượu vang": "A glass of red wine next to a wine bottle",
"khoai lang": "Roasted sweet potatoes with purple skin, one split open showing orange flesh",
"thanh long": "Dragon fruit with pink skin, one cut open showing white flesh with black seeds",
"gỏi cuốn": "Vietnamese fresh spring rolls with shrimp and herbs on a plate with dipping sauce",
"kim chi": "A bowl of Korean kimchi made of red napa cabbage",
"bánh đa": "Thin round crispy rice crackers stacked on a plate",
"dưa": "A watermelon cut in half with a slice, and a whole melon",
"mía": "Sugarcane stalks and a glass of sugarcane juice",
"ốc": "A plate of cooked snails with lemongrass and chili",
"ăn thịt": "A person eating grilled meat with chopsticks at a barbecue table",
"khu phố": "A quiet neighborhood street with small shops and houses seen from above",
"ký túc xá": "A university dormitory building with students on the balcony",
"nhà khách": "A small welcoming guest house with a front door and a lantern, no writing",
"khu công nghiệp": "An industrial park with factories and chimneys",
"bến xe buýt": "A bus stop shelter with a city bus arriving and people waiting",
"sân chơi": "A children's playground with a slide and swings",
"làng nghề": "A traditional craft village where potters make ceramics",
"núi": "A mountain landscape with peaks and clouds",
"đền": "A traditional Vietnamese temple with a curved roof and incense smoke",
"đất": "A plot of brown farmland soil with a small green sprout",
"ngoài trời": "A family eating at a table outdoors in a garden under the open sky",
"bên ngoài": "A person standing outside a door in the rain with an umbrella",
"hang động": "A cave entrance with stalactites and a small boat",
"cây xanh": "A street lined with green leafy trees",
"giày cao gót": "A pair of red high heel shoes",
"thợ may": "A tailor sewing a garment at a sewing machine with a measuring tape around the neck",
"giặt quần áo": "A washing machine with colorful clothes and a laundry basket",
"gội đầu": "A woman washing her hair with shampoo foam",
"mũ bảo hiểm": "A motorcycle helmet",
"bánh xe": "A car wheel with a black tire",
"tăng giá": "A gas pump with a big red arrow pointing up",
"miễn thuế": "Shopping bags and a suitcase in an airport duty free shop",
"mở hàng": "A market vendor woman opening her stall in the morning, first customer paying",
"tiền bạc": "A wallet with banknotes and coins",
"quần": "A pair of blue trousers",
"lụa": "Colorful rolls of silk fabric",
"may mặc": "Clothes hanging on a rack in a garment factory",
"thuê bao": "A smartphone with a SIM card and signal bars",
"tờ khai": "A paper form on a clipboard with checkboxes and a pen",
"nhập cảnh": "An airport immigration counter with an officer stamping a passport",
"mã số": "A package with a barcode label",
"hướng dẫn viên": "A tour guide holding a small flag leading tourists",
"thư điện tử": "A laptop screen showing an email envelope icon",
"xin việc": "A person handing a resume to an interviewer at a desk",
"lý lịch": "A resume document with a photo of a person and lines",
"công dân": "A person holding an ID card with a flag behind",
"thám hiểm": "An explorer with a backpack and a compass in a jungle",
"đóng cửa": "A hand pulling down a shop's rolling shutter door at night",
"đón bạn": "A person hugging a friend at an airport arrivals hall",
"bác trai": "A middle-aged uncle smiling in casual clothes",
"ông chủ": "A boss in a suit sitting behind a desk in an office",
"em bé": "A cute smiling baby",
"người quen": "Two acquaintances shaking hands and greeting on the street",
"người đẹp": "A beautiful young woman smiling in a traditional ao dai dress",
"họa sĩ": "A painter with a palette and an easel",
"nhà văn": "A writer typing at a desk with books and a lamp",
"nhà giáo": "A teacher standing in front of a classroom blackboard",
"giúp việc": "A housekeeper cleaning the living room with a mop",
"đối tác": "Two business people shaking hands over a table with documents",
"trai gái": "A boy and a girl standing together as siblings",
"thế hệ": "Three generations standing in a row: grandparent, parent and child",
"hoa hậu": "A beauty queen wearing a crown and a plain sash",
"mẹ con": "A mother holding her child's hand walking together",
"khôn ngoan": "A smart man with a big lightbulb above his head",
"xinh xắn": "A cute little girl in a pink dress smiling",
"lúng túng": "A flustered person scratching head with sweat drops, confused",
"chăm học": "A student studying hard at a desk with a pile of books",
"tốt đẹp": "A big thumbs up surrounded by sparkles and flowers",
"mới mẻ": "A person opening a brand new gift box with sparkles",
"sâu sắc": "A person deeply moved with a hand on the chest after watching a film",
"khô ráo": "Dry clothes hanging on a line under bright sun",
"cao to": "A tall broad-shouldered man standing next to a door",
"dáng vẻ": "A graceful elegant person standing in profile wearing a hat",
"mong ước": "A child looking up at a shooting star making a wish",
"tình yêu": "Two hands forming a heart shape with red hearts around",
"sức mạnh": "A strong arm flexing a big bicep",
"tuổi trẻ": "Young people laughing together riding bicycles",
"đương nhiên": "A confident person giving a thumbs up next to a big check mark",
"trân trọng": "Two hands gently holding a small glowing heart",
"nói rõ": "A person explaining clearly with a pointer at a whiteboard",
"kể lại": "A grandmother telling a story to children gathered around",
"tra cứu": "A person searching in a big dictionary book with a magnifying glass",
"học thêm": "A student in an evening tutoring class with a teacher",
"tìm thấy": "A hand finding a key under a sofa cushion with a happy face",
"đặt tên": "Parents looking at a newborn baby and thinking of a name",
"ghi nhớ": "A person writing notes into a notebook to remember, with a small brain icon",
"thúc giục": "A person pointing at a wristwatch urging another person to hurry",
"khuyên bảo": "A mother gently advising her teenage son with a hand on his shoulder",
"đem theo": "A traveler putting a passport into a backpack",
"thi đỗ": "A student jumping with joy holding an acceptance letter",
"thi đấu": "Two soccer players competing for the ball in a match",
"đá bóng": "A boy kicking a soccer ball",
"thể dục": "A person doing morning stretching exercise in a park",
"chơi điện tử": "A boy playing a video game with a controller in front of a screen",
"kháng sinh": "A blister pack of capsules and pills",
"chảy máu": "A finger with a drop of blood and a bandage",
"y học": "A stethoscope on top of a medical textbook",
"y tế": "A small health clinic building with a red cross",
"sự cố": "A factory machine sparking with a warning triangle sign",
"chân tay": "A person stretching arms and legs, front view",
"mi mắt": "A close-up of an eye with long eyelashes",
"xương": "An x-ray of a hand showing the bones",
"mỡ": "A frying pan with melted fat and a piece of pork fat",
"động tác": "An exercise instructor demonstrating a stretch pose with motion lines",
}
