JOBS = {
"kế hoạch sản xuất": "A factory manager pointing at a wall production schedule chart with colored bars",
"lệnh sản xuất": "A supervisor handing a work order paper sheet to a factory worker",
"thao tác chuẩn": "A worker following a step-by-step standard procedure poster next to a machine",
"bố trí nhân lực": "A line leader assigning workers to different stations on a factory floor",
"giao ca": "Two workers shaking hands at a shift change in front of a wall clock",
"điểm danh": "A supervisor with a clipboard checking a row of workers in uniforms",
"tăng ca": "Tired factory workers still working at night with the wall clock showing late evening",
"ca đêm": "A worker in a factory at night with a moon in the window and bright lights",
"thiếu người": "A production line with several empty workstations and one worker looking around",
"làm lại": "A worker redoing a defective product with a circular arrow symbol",
"cải tiến": "A lightbulb above a machine with an upward arrow showing improvement",
"lãng phí": "A pile of wasted material scraps being thrown into a bin, wasted",
"khởi động chuyền": "A hand pressing a big green start button on a factory conveyor line",
"dừng chuyền": "A hand pressing a big red stop button on a factory line",
"chạy thử": "A technician testing a new machine for the first time with a test tube sample",
"mục tiêu ngày": "A target board with an arrow hitting the bullseye next to a factory sign",
"đạt kế hoạch": "A team of workers celebrating with a checkmark on a chart",
"người thay ca": "A worker waving goodbye while another worker arrives to take over the station",
"báo cáo tháng": "A person presenting a monthly report with bar charts on a screen",
"trình ký": "A hand stamping a signature on a document on a manager's desk",
"phê duyệt": "A big green approved stamp on a document",
"từ chối duyệt": "A big red rejected stamp on a document",
"bản gốc": "An original document with a golden seal next to a faded copy",
"bản sao": "A photocopier producing copies of a document",
"lưu hồ sơ": "A filing cabinet with folders and a hand putting a file in",
"chi phí": "A calculator and a pile of receipts with coins",
"lợi nhuận": "A stack of coins growing with a green upward arrow",
"ngân sách": "A pie chart budget and a piggy bank",
"quyết toán": "An accountant at a desk closing the books with a calculator and ledgers",
"báo giá": "A price quotation paper with a pen and calculator",
"tạm ứng": "A hand giving an envelope of money to an employee at a desk",
"chấm dứt hợp đồng": "A contract paper being torn in half",
"đề xuất cải tiến": "A worker dropping a suggestion note into a suggestion box",
"hợp đồng lao động": "Two people signing a contract paper at a desk with a pen",
"thử việc": "A new employee wearing a probation name tag being shown around an office",
"bảng lương": "A payslip paper with coins and a calculator",
"lương cơ bản": "A single stack of banknotes with a base icon",
"phụ cấp": "A base stack of money with extra coins added on top",
"bảo hiểm xã hội": "A shield with a family under it and a document",
"nghỉ phép năm": "A person relaxing on a beach with a suitcase and a calendar",
"nghỉ ốm": "A sick person in bed with a thermometer and a medicine bottle",
"đơn xin nghỉ": "A hand writing a leave request form on paper",
"đi muộn": "A man running with a bag toward an office door while the clock shows late",
"tự ý nghỉ": "An empty desk with an absent sign and a calendar with red cross",
"khen thưởng": "A manager handing a trophy and a bonus envelope to a smiling employee",
"đánh giá năng lực": "A manager with a clipboard giving a star rating to an employee",
"bàn giao": "Two colleagues handing over a folder of documents to each other",
"công đoàn": "A group of workers raising fists together with a union flag",
"sơ yếu lý lịch": "A resume paper with a photo and lines of information",
"đình công": "A crowd of workers standing outside a factory holding blank banners",
"linh kiện điện tử": "A tray of small electronic components like resistors and chips",
"bo mạch": "A green printed circuit board with chips",
"tụ điện": "Two cylindrical electrolytic capacitors",
"điện trở": "A resistor with colored stripes",
"đầu nối": "A cable connector plug next to its socket",
"dây cáp": "A coiled black cable",
"cầu chì": "A blown fuse with a broken wire",
"hàn thiếc": "A soldering iron soldering a circuit board with smoke",
"kem hàn": "A syringe of solder paste on a circuit board",
"kiểm tra chức năng": "A technician testing a device with a multimeter and a green check",
"tỷ lệ lỗi": "A bar chart of defect rate going down next to a magnifying glass",
"lỗi hàn": "A close-up of a poor solder joint on a circuit board with a red circle",
"thiếu linh kiện": "A circuit board with an empty gap where a component is missing",
"gắn ngược": "A chip placed upside down on a board with a red X",
"vòng tay tĩnh điện": "A wrist strap for static electricity connected to a cord",
"áo phòng sạch": "A worker in a full white cleanroom suit, hood and mask",
"băng tải": "A conveyor belt carrying small boxes",
"mã vạch": "A barcode label being scanned by a red laser scanner",
"giày da": "A pair of brown leather dress shoes",
"mũ giày": "The upper part of a sneaker without a sole",
"đế giữa": "A midsole of a running shoe, foam",
"lót giày": "An insole insert of a shoe",
"dây giày": "A pair of shoelaces",
"gót giày": "The heel part of a shoe seen from behind",
"phom giày": "A wooden shoe last mold",
"da thật": "A roll of genuine brown leather hide",
"ép đế": "A machine pressing a sole onto a shoe",
"dán đế": "A worker gluing a sole onto a shoe",
"bôi keo": "A worker brushing glue onto a shoe part",
"gò giày": "A worker stretching a shoe upper over a last",
"cắt da": "A worker cutting leather with a cutting knife on a table",
"bong keo": "A shoe with the toe part peeling apart at the glue line",
"cỡ giày": "A shoe with a measuring ruler and size scale",
"giày lỗi": "A shoe with a red X mark and a crooked sole",
"hộp giày": "A stack of shoe boxes with a pair of shoes on top",
"công trường": "A construction site with cranes and scaffolding",
"thi công": "Construction workers building a wall",
"bản vẽ thiết kế": "A blueprint of a building plan with a ruler",
"giám sát": "A supervising engineer in a helmet with a clipboard on a construction site",
"nghiệm thu": "Engineers inspecting a finished building with a green check",
"bê tông": "Concrete being poured from a mixer truck",
"cốt thép": "A grid of steel reinforcement bars",
"gạch": "A stack of red bricks",
"cát": "A big pile of sand",
"cẩu": "A tower crane lifting a load",
"máy xúc": "A yellow excavator digging",
"chống thấm": "A worker applying waterproofing membrane on a roof",
"dây an toàn": "A worker on high steel beams wearing a safety harness",
"lưới an toàn": "A safety net around a building under construction",
"dự toán": "A calculator, blueprint and a stack of coins",
"móng": "A building foundation being poured in a pit",
"mái": "A house roof with tiles",
"máy tiện": "A lathe machine cutting a metal rod",
"máy phay": "A milling machine cutting metal",
"máy khoan": "A drill press drilling a hole in metal",
"máy hàn": "A welder with a mask welding metal with sparks",
"vòng bi": "A metal ball bearing",
"bơm": "A water pump machine with pipes",
"van": "A pipe valve with a red wheel handle",
"bánh răng": "Two meshing metal gears",
"bu lông": "A hex bolt",
"đai ốc": "A hex nut",
"thước cặp": "A vernier caliper measuring a small metal part",
"bảo trì định kỳ": "A technician with a wrench and a maintenance calendar next to a machine",
"bôi trơn": "An oil can dripping oil onto a machine shaft",
"quá tải": "A machine overloaded with a red warning light and heavy weights",
"rò rỉ": "A pipe leaking oil drops onto the floor",
"mất điện": "A dark factory with a broken light bulb and unplugged cord",
"kiểm tra cuối": "An inspector checking a finished product at the end of the line with a check mark",
"hàng không đạt": "Rejected products in a red bin with an X mark",
"bình chữa cháy": "A red fire extinguisher",
"kính bảo hộ": "A pair of clear safety goggles",
"kho hàng": "A large warehouse with tall shelves and boxes",
"nhập kho": "Workers carrying boxes into a warehouse",
"xuất kho": "Workers loading boxes onto a truck from a warehouse",
"kiểm kê": "A worker with a tablet counting boxes on warehouse shelves",
"xe nâng": "A forklift lifting a pallet",
"pa lét": "A wooden pallet stacked with boxes",
"bốc xếp": "Two workers loading boxes onto a truck",
"dỡ hàng": "Workers unloading boxes from a container truck",
"xe tải": "A big delivery truck",
"cảng biển": "A container port with a ship and cranes",
"niêm phong": "A hand sealing a box with a red seal sticker",
"băng keo": "A roll of packing tape",
"quầy thu ngân": "A supermarket cashier counter with a scanner",
"kệ hàng": "A supermarket shelf stocked with goods",
"trưng bày": "A store worker arranging products on a display shelf",
"đổi trả": "A customer returning a box to a store clerk at the counter",
"doanh số": "A bar chart of rising sales with a coin",
}
