# -*- coding: utf-8 -*-
"""직무 낱말 보강 (#8) — 이미 검수된 후보 풀(data/_jobwords.json, 사전 표제어인 것)에서 트랙별로 골라 예문을 붙인다.
[낱말, 뜻, 예문 vi, 예문 ko]. 트랙 이름은 order.json 의 직무 8트랙과 같다."""
TRACKS = {
"지시하고 확인하기": [
 ["kế hoạch sản xuất", "생산 계획", "Anh xem kế hoạch sản xuất tuần này chưa?", "이번 주 생산 계획 보셨어요?"],
 ["lệnh sản xuất", "작업 지시서", "Lệnh sản xuất đã được gửi xuống chuyền.", "작업 지시서가 라인에 내려갔어요."],
 ["thao tác chuẩn", "표준 작업", "Mọi người làm theo thao tác chuẩn nhé.", "모두 표준 작업대로 해 주세요."],
 ["bố trí nhân lực", "인력 배치", "Trưởng chuyền đang bố trí nhân lực cho ca đêm.", "라인장이 야간조 인력을 배치하고 있어요."],
 ["giao ca", "교대 인수인계", "Trước khi giao ca, chị nhớ ghi lại tình hình máy.", "교대하기 전에 설비 상태를 적어 두세요."],
 ["điểm danh", "출석 점검", "Sáng nào cũng điểm danh trước giờ làm.", "아침마다 근무 시작 전에 출석을 점검해요."],
 ["tăng ca", "잔업하다", "Hôm nay cả tổ phải tăng ca hai tiếng.", "오늘은 조 전체가 두 시간 잔업해야 해요."],
 ["ca đêm", "야간조", "Tuần sau tôi chuyển sang ca đêm.", "다음 주에 저는 야간조로 옮겨요."],
 ["thiếu người", "인원 부족", "Chuyền này đang thiếu người.", "이 라인은 인원이 부족해요."],
 ["làm lại", "재작업하다", "Lô hàng này phải làm lại.", "이 로트는 재작업해야 해요."],
 ["cải tiến", "개선", "Anh có ý kiến cải tiến gì không?", "개선할 의견이 있으세요?"],
 ["lãng phí", "낭비", "Chúng ta cần giảm lãng phí vật liệu.", "우리는 자재 낭비를 줄여야 해요."],
 ["khởi động chuyền", "라인 가동", "Bảy giờ sẽ khởi động chuyền.", "7시에 라인을 가동할 거예요."],
 ["dừng chuyền", "라인 정지", "Có sự cố nên phải dừng chuyền.", "문제가 생겨서 라인을 멈춰야 해요."],
 ["chạy thử", "시운전", "Anh chạy thử máy một lần nhé.", "설비를 한 번 시운전해 보세요."],
 ["mục tiêu ngày", "일일 목표", "Mục tiêu ngày hôm nay là năm trăm sản phẩm.", "오늘 일일 목표는 오백 개예요."],
 ["đạt kế hoạch", "계획 달성", "Tháng này tổ chúng ta đã đạt kế hoạch.", "이번 달 우리 조는 계획을 달성했어요."],
 ["người thay ca", "교대 대체 인력", "Chị tìm người thay ca giúp tôi được không?", "저 대신 교대할 사람을 찾아 주실 수 있어요?"],
],
"회의와 보고": [
 ["báo cáo tháng", "월간 보고", "Cuối tháng tôi phải nộp báo cáo tháng.", "월말에 저는 월간 보고를 내야 해요."],
 ["trình ký", "결재 상신", "Tôi đã trình ký lên giám đốc.", "저는 이사님께 결재를 올렸어요."],
 ["phê duyệt", "승인하다", "Giám đốc đã phê duyệt đề xuất này.", "이사님이 이 제안을 승인했어요."],
 ["từ chối duyệt", "반려하다", "Phòng kế toán từ chối duyệt hồ sơ này.", "경리팀이 이 서류를 반려했어요."],
 ["bản gốc", "원본", "Anh nhớ mang bản gốc đến nhé.", "원본을 꼭 가져오세요."],
 ["bản sao", "사본", "Chị cho tôi xin một bản sao.", "사본을 한 부 주세요."],
 ["lưu hồ sơ", "서류 보관", "Tài liệu này cần lưu hồ sơ năm năm.", "이 서류는 5년간 보관해야 해요."],
 ["chi phí", "비용", "Chi phí tháng này tăng nhiều.", "이번 달 비용이 많이 늘었어요."],
 ["lợi nhuận", "이익", "Lợi nhuận năm nay cao hơn năm ngoái.", "올해 이익이 작년보다 높아요."],
 ["ngân sách", "예산", "Ngân sách quý này còn lại bao nhiêu?", "이번 분기 예산이 얼마나 남았어요?"],
 ["quyết toán", "결산", "Phòng kế toán đang làm quyết toán cuối năm.", "경리팀이 연말 결산을 하고 있어요."],
 ["báo giá", "견적서", "Công ty đó đã gửi báo giá cho chúng tôi.", "그 회사가 우리에게 견적서를 보냈어요."],
 ["thanh toán", "정산, 결제", "Khi nào công ty thanh toán cho nhà cung cấp?", "회사는 언제 공급업체에 결제하나요?"],
 ["chuyển khoản", "계좌 이체", "Tôi sẽ chuyển khoản vào chiều nay.", "오늘 오후에 계좌 이체할게요."],
 ["tạm ứng", "가불, 선지급", "Anh ấy xin tạm ứng lương.", "그는 월급 가불을 신청했어요."],
 ["chấm dứt hợp đồng", "계약 해지", "Hai bên đã chấm dứt hợp đồng.", "양측이 계약을 해지했어요."],
 ["đề xuất cải tiến", "개선 제안", "Tôi muốn nộp một đề xuất cải tiến.", "저는 개선 제안을 하나 내고 싶어요."],
],
"인사·평가·채용": [
 ["hợp đồng lao động", "근로 계약", "Anh đã ký hợp đồng lao động chưa?", "근로 계약서에 서명하셨어요?"],
 ["thử việc", "수습", "Tôi đang trong thời gian thử việc.", "저는 수습 기간이에요."],
 ["bảng lương", "급여 명세서", "Cuối tháng công ty phát bảng lương.", "월말에 회사가 급여 명세서를 나눠 줘요."],
 ["lương cơ bản", "기본급", "Lương cơ bản của tôi là mười triệu.", "제 기본급은 천만 동이에요."],
 ["phụ cấp", "수당", "Công ty có phụ cấp ăn trưa không?", "회사에 점심 수당이 있어요?"],
 ["bảo hiểm xã hội", "사회보험", "Công ty đóng bảo hiểm xã hội cho nhân viên.", "회사가 직원의 사회보험을 내 줘요."],
 ["nghỉ phép năm", "연차 휴가", "Mỗi năm tôi được mười hai ngày nghỉ phép năm.", "저는 해마다 연차 휴가가 12일 있어요."],
 ["nghỉ ốm", "병가", "Tôi xin nghỉ ốm hai ngày.", "저는 병가를 이틀 신청해요."],
 ["đơn xin nghỉ", "휴가 신청서", "Anh viết đơn xin nghỉ rồi nộp cho trưởng phòng.", "휴가 신청서를 써서 부장님께 내세요."],
 ["đi muộn", "지각", "Tháng này tôi đi muộn hai lần.", "이번 달 저는 지각을 두 번 했어요."],
 ["tự ý nghỉ", "무단 결근", "Tự ý nghỉ sẽ bị trừ lương.", "무단 결근하면 월급이 깎여요."],
 ["khen thưởng", "포상", "Cuối năm công ty có khen thưởng nhân viên giỏi.", "연말에 회사가 우수 직원을 포상해요."],
 ["đánh giá năng lực", "인사 평가", "Tháng sau có đánh giá năng lực.", "다음 달에 인사 평가가 있어요."],
 ["bàn giao", "인수인계", "Tôi phải bàn giao công việc trước khi nghỉ.", "저는 그만두기 전에 업무를 인수인계해야 해요."],
 ["công đoàn", "노동조합", "Công đoàn tổ chức chuyến đi cho công nhân.", "노동조합이 근로자들을 위한 여행을 열어요."],
 ["sơ yếu lý lịch", "이력서", "Chị gửi sơ yếu lý lịch qua thư điện tử nhé.", "이력서를 이메일로 보내 주세요."],
 ["đình công", "파업", "Công nhân ở nhà máy đó đã đình công.", "그 공장 근로자들이 파업했어요."],
],
"전자·전기": [
 ["linh kiện điện tử", "전자부품", "Kho đã nhập thêm linh kiện điện tử.", "창고에 전자부품이 더 입고됐어요."],
 ["bo mạch", "기판(PCB)", "Bo mạch này bị lỗi rồi.", "이 기판에 불량이 났어요."],
 ["tụ điện", "콘덴서", "Anh thay tụ điện giúp tôi nhé.", "콘덴서를 교체해 주세요."],
 ["điện trở", "저항", "Điện trở này có giá trị bao nhiêu?", "이 저항은 값이 얼마예요?"],
 ["đầu nối", "커넥터", "Đầu nối bị lỏng nên máy không chạy.", "커넥터가 헐거워서 기계가 안 돌아가요."],
 ["dây cáp", "케이블", "Dây cáp này quá ngắn.", "이 케이블은 너무 짧아요."],
 ["cầu chì", "퓨즈", "Cầu chì bị cháy rồi.", "퓨즈가 나갔어요."],
 ["hàn thiếc", "납땜하다", "Chị ấy hàn thiếc rất nhanh.", "그녀는 납땜을 아주 빨리 해요."],
 ["kem hàn", "솔더 페이스트", "Kem hàn phải để trong tủ lạnh.", "솔더 페이스트는 냉장고에 넣어 둬야 해요."],
 ["kiểm tra chức năng", "기능 검사", "Sau khi lắp xong phải kiểm tra chức năng.", "조립을 마친 뒤에는 기능 검사를 해야 해요."],
 ["tỷ lệ lỗi", "불량률", "Tỷ lệ lỗi tuần này giảm rồi.", "이번 주 불량률이 내려갔어요."],
 ["lỗi hàn", "납땜 불량", "Có ba bo bị lỗi hàn.", "기판 세 장에 납땜 불량이 있어요."],
 ["thiếu linh kiện", "부품 누락", "Bo này bị thiếu linh kiện.", "이 기판은 부품이 빠졌어요."],
 ["gắn ngược", "역삽입", "Điốt này bị gắn ngược.", "이 다이오드는 거꾸로 꽂혔어요."],
 ["vòng tay tĩnh điện", "정전기 손목띠", "Vào khu vực này phải đeo vòng tay tĩnh điện.", "이 구역에 들어가려면 정전기 손목띠를 차야 해요."],
 ["áo phòng sạch", "방진복", "Mặc áo phòng sạch trước khi vào phòng.", "방에 들어가기 전에 방진복을 입으세요."],
 ["băng tải", "컨베이어", "Băng tải đang chạy chậm.", "컨베이어가 느리게 돌아가요."],
 ["mã vạch", "바코드", "Anh quét mã vạch trên khay linh kiện.", "부품 트레이의 바코드를 스캔하세요."],
],
"섬유·봉제·신발": [
 ["giày da", "구두", "Nhà máy này làm giày da xuất khẩu.", "이 공장은 수출용 구두를 만들어요."],
 ["mũ giày", "갑피", "Chuyền may đang may mũ giày.", "봉제 라인에서 갑피를 박고 있어요."],
 ["đế giữa", "미드솔", "Đế giữa của đôi này rất mềm.", "이 신발의 미드솔은 아주 말랑해요."],
 ["lót giày", "인솔, 깔창", "Anh đặt lót giày vào trước.", "먼저 깔창을 넣으세요."],
 ["dây giày", "신발끈", "Đôi này thiếu dây giày.", "이 신발은 신발끈이 빠졌어요."],
 ["gót giày", "뒷굽", "Gót giày bị lệch.", "뒷굽이 삐뚤어졌어요."],
 ["phom giày", "라스트(신발 골)", "Kho phom giày ở tầng hai.", "라스트 창고는 2층에 있어요."],
 ["da thật", "천연가죽", "Đôi giày này làm bằng da thật.", "이 신발은 천연가죽으로 만들었어요."],
 ["ép đế", "밑창 압착", "Công nhân đang ép đế.", "작업자가 밑창을 압착하고 있어요."],
 ["dán đế", "밑창 접착", "Dán đế xong phải để khô.", "밑창을 붙인 뒤에는 말려야 해요."],
 ["bôi keo", "본드 칠하기", "Bôi keo đều tay nhé.", "본드를 고르게 칠하세요."],
 ["gò giày", "라스팅", "Chuyền gò giày cần thêm hai người.", "라스팅 라인에 두 명이 더 필요해요."],
 ["cắt da", "가죽 재단", "Bộ phận cắt da làm việc từ sáng sớm.", "가죽 재단부는 이른 아침부터 일해요."],
 ["bong keo", "본드 벗겨짐", "Đôi này bị bong keo ở mũi.", "이 신발은 앞코 본드가 벗겨졌어요."],
 ["cỡ giày", "신발 치수", "Chị đi cỡ giày bao nhiêu?", "신발 치수가 어떻게 되세요?"],
 ["giày lỗi", "불량 신발", "Giày lỗi để riêng vào thùng này.", "불량 신발은 이 상자에 따로 담으세요."],
 ["hộp giày", "신발 상자", "Xếp giày vào hộp giày cho ngay ngắn.", "신발을 상자에 반듯하게 담으세요."],
],
"건설·부동산": [
 ["công trường", "공사 현장", "Sáng mai tôi ra công trường sớm.", "내일 아침 저는 일찍 공사 현장에 나가요."],
 ["thi công", "시공하다", "Nhà thầu đang thi công tầng năm.", "시공사가 5층을 시공하고 있어요."],
 ["bản vẽ thiết kế", "설계도", "Anh cho tôi xem bản vẽ thiết kế.", "설계도를 보여 주세요."],
 ["giám sát", "감리하다, 감독", "Kỹ sư giám sát kiểm tra mỗi ngày.", "감리 기사가 매일 점검해요."],
 ["nghiệm thu", "준공 검사", "Ngày mai có nghiệm thu công trình.", "내일 공사 준공 검사가 있어요."],
 ["bê tông", "콘크리트", "Hôm nay đổ bê tông sàn tầng ba.", "오늘 3층 바닥에 콘크리트를 부어요."],
 ["cốt thép", "철근", "Cốt thép phải buộc chắc chắn.", "철근을 단단히 묶어야 해요."],
 ["gạch", "벽돌", "Xe chở gạch đã đến.", "벽돌을 실은 차가 도착했어요."],
 ["cát", "모래", "Chúng ta cần thêm hai xe cát.", "모래가 두 차 더 필요해요."],
 ["cẩu", "크레인", "Cẩu đang nâng thép lên cao.", "크레인이 철강재를 높이 들어 올려요."],
 ["máy xúc", "굴착기", "Máy xúc đang đào móng.", "굴착기가 기초를 파고 있어요."],
 ["chống thấm", "방수", "Nhà vệ sinh phải chống thấm kỹ.", "화장실은 방수를 꼼꼼히 해야 해요."],
 ["dây an toàn", "안전벨트", "Làm việc trên cao phải đeo dây an toàn.", "높은 곳에서 일할 때는 안전벨트를 매야 해요."],
 ["lưới an toàn", "안전망", "Lưới an toàn được căng quanh tòa nhà.", "건물 둘레에 안전망을 쳤어요."],
 ["dự toán", "공사비 산출", "Phòng kỹ thuật đang lập dự toán.", "기술팀이 공사비를 산출하고 있어요."],
 ["móng", "기초", "Đào móng xong thì đổ bê tông.", "기초를 다 파면 콘크리트를 부어요."],
 ["mái", "지붕", "Mái nhà bị dột.", "지붕이 새요."],
],
"일반 제조·기계": [
 ["máy tiện", "선반", "Anh Nam đứng máy tiện đã mười năm.", "남 씨는 선반 앞에 선 지 십 년이에요."],
 ["máy phay", "밀링", "Máy phay này chạy rất chính xác.", "이 밀링은 아주 정확하게 돌아요."],
 ["máy khoan", "드릴링기", "Chị dùng máy khoan để khoan lỗ.", "드릴링기로 구멍을 뚫으세요."],
 ["máy hàn", "용접기", "Máy hàn bị hỏng rồi.", "용접기가 고장났어요."],
 ["vòng bi", "베어링", "Vòng bi bị mòn nên máy kêu to.", "베어링이 닳아서 기계 소리가 커요."],
 ["bơm", "펌프", "Bơm nước của xưởng đang bị nghẹt.", "공장 급수 펌프가 막혔어요."],
 ["van", "밸브", "Anh đóng van lại giúp tôi.", "밸브를 잠가 주세요."],
 ["bánh răng", "기어", "Bánh răng cần được tra dầu.", "기어에 기름을 쳐야 해요."],
 ["bu lông", "볼트", "Siết chặt bu lông này nhé.", "이 볼트를 단단히 조이세요."],
 ["đai ốc", "너트", "Có một đai ốc bị lỏng.", "너트 하나가 풀렸어요."],
 ["thước cặp", "버니어 캘리퍼스", "Dùng thước cặp để đo đường kính.", "버니어 캘리퍼스로 지름을 재세요."],
 ["bảo trì định kỳ", "정기 보전", "Máy được bảo trì định kỳ mỗi tháng.", "설비는 매달 정기 보전을 해요."],
 ["bôi trơn", "급유하다", "Nhớ bôi trơn trục trước khi chạy máy.", "설비를 돌리기 전에 축에 급유하는 걸 잊지 마세요."],
 ["quá tải", "과부하", "Máy dừng vì bị quá tải.", "과부하가 걸려서 설비가 멈췄어요."],
 ["rò rỉ", "누유, 누수", "Ống dầu bị rò rỉ.", "오일 배관에서 기름이 새요."],
 ["mất điện", "정전", "Xưởng bị mất điện từ sáng.", "공장이 아침부터 정전이에요."],
 ["kiểm tra cuối", "최종 검사", "Sản phẩm phải qua kiểm tra cuối.", "제품은 최종 검사를 거쳐야 해요."],
 ["hàng không đạt", "불합격품", "Hàng không đạt để riêng ra.", "불합격품은 따로 빼 두세요."],
 ["bình chữa cháy", "소화기", "Bình chữa cháy ở cạnh cửa.", "소화기는 문 옆에 있어요."],
 ["kính bảo hộ", "보안경", "Vào xưởng phải đeo kính bảo hộ.", "작업장에 들어가려면 보안경을 써야 해요."],
],
"유통·무역·물류": [
 ["kho hàng", "창고", "Kho hàng của công ty ở ngoại ô.", "회사 창고는 교외에 있어요."],
 ["nhập kho", "입고하다", "Hàng sẽ nhập kho chiều nay.", "물건이 오늘 오후에 입고돼요."],
 ["xuất kho", "출고하다", "Anh làm phiếu để xuất kho.", "출고 전표를 만드세요."],
 ["kiểm kê", "재고 조사", "Cuối tháng cả kho phải kiểm kê.", "월말에 창고 전체가 재고 조사를 해요."],
 ["xe nâng", "지게차", "Anh lái xe nâng được không?", "지게차를 운전할 수 있어요?"],
 ["pa lét", "팔레트", "Xếp thùng hàng lên pa lét.", "상자를 팔레트에 쌓으세요."],
 ["bốc xếp", "상하차", "Công nhân bốc xếp đang làm việc.", "상하차 작업자들이 일하고 있어요."],
 ["dỡ hàng", "하역하다", "Xe container đang dỡ hàng.", "컨테이너 차가 짐을 내리고 있어요."],
 ["xe tải", "트럭", "Xe tải này chở được năm tấn.", "이 트럭은 5톤을 실을 수 있어요."],
 ["cảng biển", "항구", "Hàng đã đến cảng biển Hải Phòng.", "물건이 하이퐁 항구에 도착했어요."],
 ["niêm phong", "봉인하다", "Thùng hàng đã được niêm phong.", "상자가 봉인됐어요."],
 ["băng keo", "포장 테이프", "Cho tôi một cuộn băng keo.", "포장 테이프 한 롤 주세요."],
 ["quầy thu ngân", "계산대", "Quầy thu ngân ở bên phải.", "계산대는 오른쪽에 있어요."],
 ["kệ hàng", "진열대", "Kệ hàng này còn trống.", "이 진열대가 비어 있어요."],
 ["trưng bày", "진열하다", "Chị trưng bày hàng mới ra phía trước.", "신상품을 앞쪽에 진열하세요."],
 ["giảm giá", "할인하다", "Cuối tuần cửa hàng giảm giá ba mươi phần trăm.", "주말에 매장이 30% 할인해요."],
 ["đổi trả", "교환·반품", "Hàng lỗi được đổi trả trong bảy ngày.", "불량품은 7일 안에 교환·반품할 수 있어요."],
 ["doanh số", "매출액", "Doanh số tháng này tăng khá cao.", "이번 달 매출액이 꽤 늘었어요."],
],
}
