# -*- coding: utf-8 -*-
"""서브교재·줌 자료 OCR 후보에서 골라 일상회화에 '보강' 세션으로 붙일 낱말. [낱말, 뜻, 예문(vi), 예문(ko)]"""
SESSIONS = [
("보강 · 달 이름", [
 ["tháng một", "1월", "Tháng một ở Hà Nội rất lạnh.", "1월의 하노이는 아주 추워요."],
 ["tháng hai", "2월", "Tháng hai có Tết.", "2월에는 설이 있어요."],
 ["tháng ba", "3월", "Sinh nhật tôi vào tháng ba.", "제 생일은 3월이에요."],
 ["tháng tư", "4월 (tháng bốn 이라 하지 않는다)", "Tháng tư trời bắt đầu nóng.", "4월이면 날씨가 더워지기 시작해요."],
 ["tháng năm", "5월", "Tháng năm tôi đi du lịch.", "5월에 저는 여행을 가요."],
 ["tháng sáu", "6월", "Tháng sáu ở đây hay mưa.", "6월에 여기는 비가 자주 와요."],
 ["tháng bảy", "7월", "Tháng bảy con tôi nghỉ hè.", "7월에 우리 아이는 여름방학이에요."],
 ["tháng tám", "8월", "Tháng tám tôi về Hàn Quốc.", "8월에 저는 한국에 돌아가요."],
 ["tháng chín", "9월", "Tháng chín trường bắt đầu học.", "9월에 학교가 개학해요."],
 ["tháng mười", "10월", "Tháng mười trời mát hơn.", "10월에는 날씨가 더 시원해요."],
 ["tháng mười một", "11월", "Tháng mười một tôi rất bận.", "11월에 저는 아주 바빠요."],
 ["tháng mười hai", "12월", "Tháng mười hai có lễ Giáng sinh.", "12월에는 크리스마스가 있어요."],
]),
("보강 · 때와 인사 표현", [
 ["ngày kia", "모레", "Ngày kia tôi đi Hà Nội.", "모레 저는 하노이에 가요."],
 ["ngày hôm nay", "오늘 하루", "Ngày hôm nay tôi rất bận.", "오늘 하루 저는 아주 바빠요."],
 ["ngày nay", "요즘, 오늘날", "Ngày nay ai cũng có điện thoại.", "요즘은 누구나 휴대전화가 있어요."],
 ["ngày xưa", "옛날", "Ngày xưa nhà tôi ở quê.", "옛날에 우리 집은 시골에 있었어요."],
 ["năm mới", "새해", "Chúc mừng năm mới!", "새해 복 많이 받으세요!"],
 ["lần nữa", "한 번 더", "Anh nói lần nữa được không?", "한 번 더 말씀해 주시겠어요?"],
 ["mọi lúc", "언제나, 아무 때나", "Chị gọi cho tôi mọi lúc nhé.", "언제든지 저에게 전화하세요."],
 ["hầu như", "거의", "Hầu như ngày nào tôi cũng đi bộ.", "저는 거의 매일 걸어요."],
 ["bỗng nhiên", "갑자기", "Bỗng nhiên trời mưa to.", "갑자기 비가 많이 왔어요."],
 ["về sớm", "일찍 돌아가다", "Hôm nay tôi về sớm.", "오늘은 제가 일찍 들어가요."],
 ["giờ phút", "순간, 때", "Giờ phút này tôi rất vui.", "지금 이 순간 저는 아주 기뻐요."],
 ["tôi đi nhé", "저 갈게요", "Muộn rồi, tôi đi nhé!", "늦었네요, 저 갈게요!"],
 ["quý vị", "여러분 (존칭)", "Xin chào quý vị!", "여러분 안녕하세요!"],
 ["chào các bạn", "여러분 안녕 (친구들에게)", "Chào các bạn, mình là Nam.", "여러분 안녕, 나는 남이야."],
]),
("보강 · 이어 주는 말과 강조", [
 ["cho nên", "그래서", "Trời mưa, cho nên tôi ở nhà.", "비가 와서 저는 집에 있어요."],
 ["bởi vậy", "그러니까, 그래서", "Bởi vậy tôi không đi.", "그래서 저는 안 가요."],
 ["vì thế", "그 때문에", "Vì thế chúng tôi đến muộn.", "그 때문에 우리는 늦게 도착했어요."],
 ["tuy vậy", "그렇지만, 그럼에도", "Món này đắt, tuy vậy rất ngon.", "이 음식은 비싸지만 아주 맛있어요."],
 ["vậy mà", "그런데도", "Tôi ngủ sớm, vậy mà vẫn mệt.", "일찍 잤는데도 여전히 피곤해요."],
 ["thế mà", "그런데도 (뜻밖)", "Nhìn nhỏ thế mà nặng lắm.", "작아 보이는데도 아주 무거워요."],
 ["nhờ có", "~ 덕분에", "Nhờ có bạn, tôi làm xong việc.", "네 덕분에 일을 끝냈어요."],
 ["hết sức", "최선을 다해, 매우", "Tôi sẽ hết sức cố gắng.", "저는 최선을 다해 노력할게요."],
 ["không hề", "전혀 ~않다", "Tôi không hề biết chuyện đó.", "저는 그 일을 전혀 몰랐어요."],
 ["biết bao", "얼마나 ~인지", "Vui biết bao khi gặp lại bạn!", "너를 다시 만나서 얼마나 기쁜지!"],
 ["đến mức", "~할 정도로", "Tôi mệt đến mức không muốn ăn.", "저는 먹기 싫을 정도로 피곤해요."],
 ["ai đó", "누군가", "Ai đó đang gõ cửa.", "누군가 문을 두드려요."],
 ["gì nữa", "또 뭐, 그 밖에 무엇", "Anh còn cần gì nữa không?", "또 필요한 게 있으세요?"],
 ["phần nào", "어느 정도", "Tôi hiểu phần nào.", "저는 어느 정도 이해해요."],
 ["có điều", "다만, 그런데", "Món này ngon, có điều hơi cay.", "이 음식은 맛있는데 다만 좀 매워요."],
]),
("보강 · 가리키기와 묻기", [
 ["cái gì", "무엇", "Đây là cái gì?", "이것은 무엇이에요?"],
 ["cái này", "이것", "Cho tôi cái này.", "이것 주세요."],
 ["cái kia", "저것", "Cái kia giá bao nhiêu?", "저것은 얼마예요?"],
 ["thế này", "이렇게", "Anh làm thế này nhé.", "이렇게 하세요."],
 ["như thế", "그렇게, 그와 같이", "Đừng nói như thế.", "그렇게 말하지 마세요."],
 ["việc gì", "무슨 일", "Anh có việc gì không?", "무슨 일 있으세요?"],
 ["không thích", "좋아하지 않다", "Tôi không thích ăn cay.", "저는 매운 걸 안 좋아해요."],
 ["khi nào cũng", "언제나", "Khi nào cũng có người giúp tôi.", "언제나 저를 도와주는 사람이 있어요."],
 ["nói chung", "일반적으로", "Nói chung người Hà Nội dậy sớm.", "일반적으로 하노이 사람들은 일찍 일어나요."],
 ["nói riêng", "특히, 개별적으로", "Tôi thích nhiều món, nói riêng là phở.", "저는 여러 음식을 좋아하지만 특히 쌀국수를 좋아해요."],
 ["tùy theo", "~에 따라", "Giá thay đổi tùy theo mùa.", "가격은 계절에 따라 바뀌어요."],
 ["trên dưới", "위아래, 약 ~쯤", "Anh ấy trên dưới bốn mươi tuổi.", "그분은 마흔 살쯤 되었어요."],
]),
("보강 · 음식과 음료", [
 ["đồ uống", "음료", "Chị muốn gọi đồ uống gì?", "어떤 음료를 주문하시겠어요?"],
 ["cà phê sữa", "연유 커피", "Cho tôi một ly cà phê sữa đá.", "연유 아이스커피 한 잔 주세요."],
 ["nước dừa", "코코넛 주스", "Trời nóng nên tôi uống nước dừa.", "더워서 저는 코코넛 주스를 마셔요."],
 ["nước chanh", "레몬(라임) 주스", "Cho tôi một ly nước chanh.", "레몬 주스 한 잔 주세요."],
 ["rượu vang", "와인", "Tối nay chúng ta uống rượu vang nhé.", "오늘 저녁에 우리 와인 마셔요."],
 ["khoai lang", "고구마", "Tôi thích ăn khoai lang nướng.", "저는 군고구마를 좋아해요."],
 ["thanh long", "용과", "Thanh long ở đây rất ngọt.", "여기 용과는 아주 달아요."],
 ["gỏi cuốn", "월남쌈(생 스프링롤)", "Gỏi cuốn chấm với nước mắm.", "월남쌈은 느억맘에 찍어 먹어요."],
 ["kim chi", "김치", "Người Hàn Quốc ăn kim chi mỗi ngày.", "한국 사람들은 매일 김치를 먹어요."],
 ["bánh đa", "쌀과자, 쌀국수 면 (종류)", "Bà bán bánh đa ở chợ.", "할머니가 시장에서 쌀과자를 팔아요."],
 ["dưa", "참외·수박류, 절임채소", "Mùa hè tôi hay ăn dưa hấu.", "여름에 저는 수박을 자주 먹어요."],
 ["mía", "사탕수수", "Nước mía uống rất mát.", "사탕수수 주스는 마시면 아주 시원해요."],
 ["ốc", "달팽이, 고둥", "Chúng tôi đi ăn ốc buổi tối.", "우리는 저녁에 달팽이 요리를 먹으러 가요."],
 ["ăn thịt", "고기를 먹다", "Tối nay tôi muốn ăn thịt.", "오늘 저녁엔 고기를 먹고 싶어요."],
]),
("보강 · 동네와 장소", [
 ["khu phố", "동네, 거리 구역", "Khu phố này rất yên tĩnh.", "이 동네는 아주 조용해요."],
 ["ký túc xá", "기숙사", "Sinh viên ở ký túc xá.", "학생들은 기숙사에 살아요."],
 ["nhà khách", "게스트하우스", "Chúng tôi ở nhà khách một đêm.", "우리는 게스트하우스에서 하룻밤 묵었어요."],
 ["khu công nghiệp", "산업단지", "Công ty tôi ở khu công nghiệp.", "우리 회사는 산업단지에 있어요."],
 ["bến xe buýt", "버스 정류장", "Bến xe buýt ở gần đây không?", "버스 정류장이 이 근처에 있어요?"],
 ["sân chơi", "놀이터", "Bọn trẻ chơi ở sân chơi.", "아이들이 놀이터에서 놀아요."],
 ["làng nghề", "수공예 전통 마을", "Chúng tôi thăm một làng nghề gốm.", "우리는 도자기 전통 마을을 방문했어요."],
 ["núi", "산", "Cuối tuần tôi leo núi.", "주말에 저는 산에 올라요."],
 ["đền", "사당, 신전", "Người ta đến đền để cầu may.", "사람들은 행운을 빌러 사당에 가요."],
 ["đất", "땅, 흙", "Anh ấy mua một mảnh đất ở quê.", "그는 시골에 땅을 샀어요."],
 ["ngoài trời", "야외", "Tối nay ta ăn ngoài trời nhé.", "오늘 저녁은 야외에서 먹어요."],
 ["bên ngoài", "바깥", "Bên ngoài trời đang mưa.", "바깥에 비가 오고 있어요."],
 ["hang động", "동굴", "Chúng tôi vào tham quan hang động.", "우리는 동굴을 구경하러 들어갔어요."],
 ["cây xanh", "초목, 푸른 나무", "Thành phố này có nhiều cây xanh.", "이 도시에는 푸른 나무가 많아요."],
]),
("보강 · 입고 씻고 사고 팔기", [
 ["giày cao gót", "하이힐", "Chị ấy đi giày cao gót đến công ty.", "그녀는 하이힐을 신고 회사에 와요."],
 ["thợ may", "재단사", "Tôi nhờ thợ may sửa cái áo này.", "저는 재단사에게 이 옷을 고쳐 달라고 부탁해요."],
 ["giặt quần áo", "빨래하다", "Cuối tuần tôi giặt quần áo.", "주말에 저는 빨래를 해요."],
 ["gội đầu", "머리를 감다", "Sáng nào tôi cũng gội đầu.", "저는 아침마다 머리를 감아요."],
 ["mũ bảo hiểm", "헬멧", "Đi xe máy phải đội mũ bảo hiểm.", "오토바이를 탈 때는 헬멧을 써야 해요."],
 ["bánh xe", "바퀴", "Bánh xe sau bị xẹp rồi.", "뒷바퀴가 바람이 빠졌어요."],
 ["tăng giá", "값이 오르다", "Xăng lại tăng giá rồi.", "휘발유가 또 올랐어요."],
 ["miễn thuế", "면세", "Cửa hàng miễn thuế ở sân bay.", "공항에 면세점이 있어요."],
 ["mở hàng", "장사를 시작하다 (첫 손님)", "Chị ơi, mua giúp em để mở hàng nhé!", "언니, 첫 손님으로 좀 사 주세요!"],
 ["tiền bạc", "돈, 금전", "Tiền bạc không phải là tất cả.", "돈이 전부는 아니에요."],
 ["quần", "바지", "Tôi muốn mua một cái quần mới.", "저는 새 바지를 사고 싶어요."],
 ["lụa", "비단", "Áo dài làm bằng lụa rất đẹp.", "비단으로 만든 아오자이는 아주 예뻐요."],
 ["may mặc", "옷 짓기, 의류", "Chị ấy làm ở công ty may mặc.", "그녀는 의류 회사에서 일해요."],
 ["thuê bao", "가입자, 회선(휴대전화 번호)", "Số thuê bao này không liên lạc được.", "이 번호는 연결되지 않아요."],
]),
("보강 · 서류와 여행", [
 ["tờ khai", "신고서, 양식", "Anh điền vào tờ khai này nhé.", "이 신고서에 기입해 주세요."],
 ["nhập cảnh", "입국", "Tôi làm thủ tục nhập cảnh ở sân bay.", "저는 공항에서 입국 수속을 해요."],
 ["mã số", "번호, 코드", "Anh cho tôi mã số của anh.", "번호를 알려 주세요."],
 ["hướng dẫn viên", "가이드", "Hướng dẫn viên nói tiếng Hàn rất giỏi.", "가이드가 한국어를 아주 잘해요."],
 ["thư điện tử", "이메일", "Chị gửi thư điện tử cho tôi nhé.", "저에게 이메일 보내 주세요."],
 ["xin việc", "구직하다, 일자리를 구하다", "Anh ấy đang đi xin việc.", "그는 일자리를 구하러 다니고 있어요."],
 ["lý lịch", "이력, 신상 정보", "Tôi đã nộp lý lịch cho công ty.", "저는 회사에 이력서를 냈어요."],
 ["công dân", "시민, 국민", "Công dân Hàn Quốc được miễn thị thực.", "한국 국민은 비자가 면제돼요."],
 ["quốc kỳ", "국기", "Quốc kỳ Việt Nam màu đỏ có ngôi sao vàng.", "베트남 국기는 빨간 바탕에 노란 별이 있어요."],
 ["thám hiểm", "탐험하다", "Anh ấy thích đi thám hiểm.", "그는 탐험 다니는 걸 좋아해요."],
 ["đóng cửa", "문을 닫다, 문 닫다", "Cửa hàng đóng cửa lúc chín giờ.", "가게는 9시에 문을 닫아요."],
 ["đón bạn", "친구를 마중하다", "Tôi ra sân bay đón bạn.", "저는 친구를 마중하러 공항에 나가요."],
]),
("보강 · 사람과 관계", [
 ["bác trai", "큰아버지, 아저씨(부모 연배 남자)", "Bác trai tôi sống ở Đà Nẵng.", "우리 큰아버지는 다낭에 사세요."],
 ["ông chủ", "사장님, 주인", "Ông chủ đang họp.", "사장님은 회의 중이에요."],
 ["em bé", "아기", "Em bé đang ngủ.", "아기가 자고 있어요."],
 ["người quen", "아는 사람", "Tôi có một người quen ở Huế.", "저는 후에에 아는 사람이 있어요."],
 ["người đẹp", "미인", "Cô ấy là một người đẹp.", "그녀는 미인이에요."],
 ["họa sĩ", "화가", "Chú tôi là họa sĩ.", "우리 삼촌은 화가예요."],
 ["nhà văn", "작가", "Nhà văn này rất nổi tiếng.", "이 작가는 아주 유명해요."],
 ["nhà giáo", "교육자, 교사", "Mẹ tôi là nhà giáo.", "우리 어머니는 교사세요."],
 ["giúp việc", "가사도우미", "Nhà tôi có người giúp việc.", "우리 집에는 가사도우미가 있어요."],
 ["đối tác", "협력 상대, 파트너", "Chúng tôi gặp đối tác hôm nay.", "우리는 오늘 협력사를 만나요."],
 ["trai gái", "남녀, 아들딸", "Nhà anh ấy có hai trai gái.", "그 집에는 아들딸이 둘 있어요."],
 ["thế hệ", "세대", "Thế hệ trẻ thích dùng điện thoại.", "젊은 세대는 휴대전화를 즐겨 써요."],
 ["hoa hậu", "미스 (미인대회 우승자)", "Cô ấy được chọn làm hoa hậu.", "그녀는 미스로 뽑혔어요."],
 ["mẹ con", "엄마와 아이", "Hai mẹ con đang đi chợ.", "엄마와 아이가 시장에 가고 있어요."],
]),
("보강 · 성격과 느낌", [
 ["khôn ngoan", "현명한, 영리한", "Anh ấy là người khôn ngoan.", "그는 현명한 사람이에요."],
 ["xinh xắn", "예쁘장한, 귀여운", "Em bé này xinh xắn quá!", "이 아기는 정말 귀여워요!"],
 ["lúng túng", "당황하는, 어쩔 줄 모르는", "Tôi lúng túng khi nói tiếng Việt.", "저는 베트남어를 말할 때 당황해요."],
 ["chăm học", "공부를 열심히 하는", "Con gái tôi rất chăm học.", "우리 딸은 공부를 아주 열심히 해요."],
 ["tốt đẹp", "좋은, 훌륭한", "Chúc anh mọi điều tốt đẹp.", "모든 일이 잘되시길 바랍니다."],
 ["mới mẻ", "새로운, 신선한", "Mọi thứ ở đây đều mới mẻ với tôi.", "여기 모든 것이 저에겐 새로워요."],
 ["sâu sắc", "깊은, 깊이 있는", "Bộ phim để lại ấn tượng sâu sắc.", "그 영화는 깊은 인상을 남겼어요."],
 ["khô ráo", "보송보송한, 마른", "Trời nắng nên quần áo khô ráo.", "날이 맑아서 옷이 보송보송해요."],
 ["cao to", "키가 크고 체격 좋은", "Anh ấy cao to lắm.", "그는 키도 크고 체격도 아주 좋아요."],
 ["dáng vẻ", "모습, 몸가짐", "Dáng vẻ chị ấy rất thanh lịch.", "그녀의 모습은 아주 우아해요."],
 ["mong ước", "소망하다, 소망", "Mong ước của tôi là mở một quán cà phê.", "제 소망은 카페를 여는 거예요."],
 ["tình yêu", "사랑", "Tình yêu cần sự tin tưởng.", "사랑에는 믿음이 필요해요."],
 ["sức mạnh", "힘, 능력", "Đoàn kết tạo nên sức mạnh.", "단결은 힘을 만들어요."],
 ["tuổi trẻ", "젊은 시절, 청춘", "Tôi nhớ tuổi trẻ của mình.", "저는 제 젊은 시절이 그리워요."],
 ["đương nhiên", "당연히", "Đương nhiên tôi sẽ đến.", "당연히 저는 갈 거예요."],
 ["trân trọng", "소중히 여기다, 정중히", "Tôi rất trân trọng tình bạn này.", "저는 이 우정을 아주 소중히 여겨요."],
]),
("보강 · 공부와 일, 하는 일", [
 ["nói rõ", "분명히 말하다", "Anh nói rõ hơn được không?", "더 분명히 말씀해 주시겠어요?"],
 ["kể lại", "다시 이야기하다", "Chị kể lại chuyện hôm qua đi.", "어제 일을 다시 이야기해 보세요."],
 ["tra cứu", "찾아보다, 조회하다", "Tôi tra cứu từ này trên mạng.", "저는 이 낱말을 인터넷에서 찾아봐요."],
 ["học thêm", "추가로 배우다, 과외", "Con tôi đi học thêm buổi tối.", "우리 아이는 저녁에 보충 수업을 가요."],
 ["tìm thấy", "찾아내다", "Tôi tìm thấy chìa khóa rồi.", "열쇠를 찾았어요."],
 ["đặt tên", "이름을 짓다", "Vợ chồng tôi đang đặt tên cho con.", "우리 부부는 아이 이름을 짓고 있어요."],
 ["ghi nhớ", "기억해 두다", "Anh hãy ghi nhớ địa chỉ này.", "이 주소를 기억해 두세요."],
 ["thúc giục", "재촉하다", "Đừng thúc giục tôi.", "저를 재촉하지 마세요."],
 ["khuyên bảo", "타이르다, 충고하다", "Mẹ luôn khuyên bảo tôi.", "어머니는 늘 저에게 충고해 주세요."],
 ["đem theo", "가져가다, 지참하다", "Anh nhớ đem theo hộ chiếu.", "여권을 꼭 가져가세요."],
 ["thi đỗ", "시험에 합격하다", "Em ấy thi đỗ đại học rồi.", "그 애는 대학에 합격했어요."],
 ["thi đấu", "경기하다", "Đội Việt Nam thi đấu tối nay.", "베트남 팀이 오늘 밤 경기해요."],
 ["đá bóng", "축구하다", "Chiều nào tôi cũng đá bóng.", "저는 오후마다 축구를 해요."],
 ["thể dục", "체육, 운동", "Sáng nào tôi cũng tập thể dục.", "저는 아침마다 운동해요."],
 ["chơi điện tử", "게임하다", "Con trai tôi thích chơi điện tử.", "우리 아들은 게임하는 걸 좋아해요."],
 ["thời khóa biểu", "시간표", "Anh xem thời khóa biểu chưa?", "시간표 보셨어요?"],
]),
("보강 · 몸과 건강", [
 ["kháng sinh", "항생제", "Bác sĩ cho tôi thuốc kháng sinh.", "의사가 저에게 항생제를 줬어요."],
 ["chảy máu", "피가 나다", "Ngón tay tôi bị chảy máu.", "제 손가락에서 피가 나요."],
 ["y học", "의학", "Em gái tôi học y học.", "제 여동생은 의학을 공부해요."],
 ["y tế", "의료, 보건", "Trạm y tế ở gần nhà tôi.", "보건소가 우리 집 근처에 있어요."],
 ["sự cố", "사고, 문제", "Có sự cố ở nhà máy.", "공장에 사고가 났어요."],
 ["chân tay", "팔다리", "Chân tay tôi đau nhức.", "제 팔다리가 쑤셔요."],
 ["mi mắt", "눈꺼풀", "Mi mắt tôi hơi sưng.", "제 눈꺼풀이 좀 부었어요."],
 ["xương", "뼈", "Anh ấy bị đau xương.", "그는 뼈가 아파요."],
 ["mỡ", "기름, 지방", "Tôi không ăn nhiều mỡ.", "저는 기름진 것을 많이 안 먹어요."],
 ["động tác", "동작", "Chị làm theo động tác của cô giáo.", "선생님의 동작을 따라 하세요."],
]),
]
